/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_customformatdata_free(a: number): void;
export function __wbg_get_customformatdata_id(a: number, b: number): void;
export function __wbg_set_customformatdata_id(a: number, b: number, c: number): void;
export function __wbg_get_customformatdata_value(a: number): number;
export function __wbg_set_customformatdata_value(a: number, b: number): void;
export function __wbg_header_free(a: number): void;
export function __wbg_get_header_magic(a: number): number;
export function __wbg_set_header_magic(a: number, b: number): void;
export function __wbg_get_header_save_game_version(a: number): number;
export function __wbg_set_header_save_game_version(a: number, b: number): void;
export function __wbg_get_header_package_version(a: number): number;
export function __wbg_set_header_package_version(a: number, b: number): void;
export function __wbg_get_header_engine_version_major(a: number): number;
export function __wbg_set_header_engine_version_major(a: number, b: number): void;
export function __wbg_get_header_engine_version_minor(a: number): number;
export function __wbg_set_header_engine_version_minor(a: number, b: number): void;
export function __wbg_get_header_engine_version_patch(a: number): number;
export function __wbg_set_header_engine_version_patch(a: number, b: number): void;
export function __wbg_get_header_engine_version_build(a: number): number;
export function __wbg_set_header_engine_version_build(a: number, b: number): void;
export function __wbg_get_header_engine_version(a: number, b: number): void;
export function __wbg_set_header_engine_version(a: number, b: number, c: number): void;
export function __wbg_get_header_custom_format_version(a: number): number;
export function __wbg_set_header_custom_format_version(a: number, b: number): void;
export function __wbg_get_header_custom_format(a: number, b: number): void;
export function __wbg_set_header_custom_format(a: number, b: number, c: number): void;
export function __wbg_root_free(a: number): void;
export function __wbg_get_root_worldSaveData(a: number): number;
export function __wbg_set_root_worldSaveData(a: number, b: number): void;
export function __wbg_save_free(a: number): void;
export function __wbg_get_save_header(a: number): number;
export function __wbg_set_save_header(a: number, b: number): void;
export function __wbg_get_save_root(a: number): number;
export function __wbg_set_save_root(a: number, b: number): void;
export function __wbg_get_save_extra(a: number): number;
export function __wbg_set_save_extra(a: number, b: number): void;
export function __wbg_buffer_free(a: number): void;
export function buffer_new(a: number, b: number): number;
export function palFromRaw(a: number, b: number, c: number, d: number): void;
export function deserialize(a: number, b: number, c: number, d: number): void;
export function __wbg_get_root_SaveGameType(a: number, b: number): void;
export function __wbg_set_root_SaveGameType(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h34ac7534ab213db2(a: number, b: number, c: number, d: number): void;
